name: HFR Update

on: 
  - push
  - workflow_dispatch

env:
  HFR_LOGIN: ${{ vars.HFR_LOGIN }}
  HFR_PASSWD: ${{ secrets.HFR_PASSWD }}

jobs:
  update-hfr:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: fp
        uses: Niks4925/git2hfr-action@main
        with:
          login: ${{ vars.HFR_LOGIN }}
          file: fp.bb
          cat: 5
          post: 204789
          response: 15123547
        env:
          HFR_PASSWD: ${{ secrets.HFR_PASSWD }}

      - name: 2nd post
        uses: Niks4925/git2hfr-action@main
        with:
          login: ${{ vars.HFR_LOGIN }}
          file: 2nd_post.bb
          cat: 5
          post: 204789
          response: 15123567
        env:
          HFR_PASSWD: ${{ secrets.HFR_PASSWD }}
